const products = [
  {
    _id: "1",
    name: "Airepods Wireless",
    image: "/images/airpod.jpg",
    description:
      "A LONG DESCRIPTION ABOUT your airpods lol lollololollolololol",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Iphone 11 pro 256GB Memory",
    image: "/images/phone.jpg",
    description:
      "A LONG DESCRIPTION ABOUT your iphoneeeee lol lollololollolololol",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Iphone 11 pro 256GB Memory",
    image: "/images/phone.jpg",
    description:
      "A LONG DESCRIPTION ABOUT your iphoneeeee lol lollololollolololol",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Iphone 11 pro 256GB Memory",
    image: "/images/phone.jpg",
    description:
      "A LONG DESCRIPTION ABOUT your iphoneeeee lol lollololollolololol",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Iphone 11 pro 256GB Memory",
    image: "/images/phone.jpg",
    description:
      "A LONG DESCRIPTION ABOUT your iphoneeeee lol lollololollolololol",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
];
